1. Importe numpy como 'np' e imprima o número da versão instalada no ambiente (local ou colab).

In [1]:
import numpy
print(numpy.__version__)

1.23.4


2. Crie um array 1D com números de 0 a 9 e imprima o resultado.

In [46]:
import numpy as np
vetor = np.arange(10)
print(f'O resultado é: {vetor}')

O resultado é: [0 1 2 3 4 5 6 7 8 9]


3. Crie uma matriz booleana de 3x3 e preencha os seus valores com 'True'. Imprima o resultado.
Dica: Verifique o uso da função full na documentação do numpy.

In [7]:
import numpy as np
vetor = np.full((3, 3), True)
print(f'O resultado é: {vetor}')

O resultado é: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4. Crie um array 1D como números inteiros (50 elementos) de 0 a 1000 aleatorios, e extraia apenas os números pares. Imprima o resultado.

In [57]:
import numpy as np
aleatorio = np.random.randint(0,1001,50)
pares = aleatorio[aleatorio % 2 == 0]
print(f'Os numeros pares são: {pares}')

Os numeros pares são: [868 280 300 646 194 828 120 658 446 558 792 726  34 154 276 298 262 542
 956 724 886 690  16 892 474 408]


5. Usando o array criando no exercício anterior, substitua todos os números ímpares maiores que 50 por -1 no array original.

In [62]:
aleatorio[(aleatorio >50) & (aleatorio % 2 == 0)], -1
aleatorio

array([868, 280, 471, 759, 967, 300, 503, 646, 915, 194, 443, 777, 767,
       828, 367, 120, 658, 849, 446, 558, 792, 726,  34, 859, 123, 154,
        35, 276, 298, 729, 262, 542, 956, 215, 724, 775, 886, 690,  16,
       309,  61, 892, 123, 325, 474, 375, 891, 408, 883, 129])

6. Usando o array criando no exercício anterior, substitua todos os números ímpares com o valor -1 sem alterar o array original.

In [19]:
impares = np.where(aleatorio % 2 == 0, aleatorio, -1)
impares

array([ -1, 950,  -1,  -1, 216,  -1, 368, 662,  -1, 760,  -1, 168, 406,
       410,  -1,  26, 750, 602,  -1,  -1, 666, 942, 586,  -1, 804, 114,
        -1, 660, 468, 774, 980, 370,  -1, 310, 968,  -1,   4,  -1, 564,
        -1,  -1,  -1, 808, 994,  -1,  -1, 970,  -1, 952,  -1])

7. Crie um array 1D com 100 valores de ponto flutuante (float), converta-o em uma matriz 2D com 10 linhas e 10 colunas.

In [23]:
import numpy as np

vetor = np.random.rand(10,10)
vetor

array([[0.15231262, 0.68686727, 0.58588508, 0.97803739, 0.16755209,
        0.13850582, 0.01712024, 0.13235737, 0.3508807 , 0.53826803],
       [0.93771452, 0.92933332, 0.4674748 , 0.41627586, 0.33554537,
        0.66638528, 0.89413747, 0.17437324, 0.8098801 , 0.77282734],
       [0.72475194, 0.52928971, 0.53561033, 0.41680495, 0.58731883,
        0.30478378, 0.68641653, 0.39820551, 0.6125247 , 0.47457442],
       [0.81970112, 0.55437829, 0.06426394, 0.55143827, 0.082575  ,
        0.73535381, 0.87520627, 0.62388992, 0.49288229, 0.62992382],
       [0.80022358, 0.78848287, 0.81564939, 0.32116846, 0.13792919,
        0.85931275, 0.88929026, 0.79946823, 0.91092246, 0.04282729],
       [0.37934815, 0.18143721, 0.49584323, 0.6243417 , 0.01413788,
        0.72801253, 0.41488885, 0.3673172 , 0.71983527, 0.09969122],
       [0.48861278, 0.73206367, 0.75024471, 0.96260729, 0.53472023,
        0.24957693, 0.64907657, 0.77043004, 0.5686936 , 0.24127799],
       [0.69873284, 0.12027584, 0.7601091

8. Crie duas matrizes 2D de inteiros aleatórios (de 0 a 100) com dimensões 10x10. Empilhe-as horizontalmente.
Dica: verique as funções hstack e concatenate na documentação do numpy

In [54]:
import numpy as np

A = np.random.randint(0,101,(10,10))
B = np.random.randint(0,101,(10,10))
concat_horiz = np.hstack((A,B))
concat_horiz
#concat_horiz.shape
np.concatenate([A,B],axis=1).shape # axis 1 aumenta linha 

(10, 20)

9. Crie duas matrizes 2D de inteiros aleatórios (de 0 a 100) com dimensões 10x10. Empilhe-as verticalmente.
Dica: verique as funções vstack e concatenate na documentação do numpy

In [56]:
import numpy as np

A = np.random.randint(0,100,(10,10))
B = np.random.randint(0,100,(10,10))
concat_vert = np.vstack((A,B))
concat_vert
#concat_vert.shape
np.concatenate([A,B],axis=0).shape # axis 0 aumenta coluna 

(20, 10)

Para ler arquivos em formato txt que estão em formato de "tabelas", podemos usar a função genfromtxt() do numpy. Esta função recebe como argumentos: caminho do arquivo txt (path local ou uma url); delimiter para separar cada valor seguindo algum critério; dtype para converter os valores recebidos em algum tipo de dado conhecido (exemplo: float) e; usecols em que é definido o cabeçalho das colunas lidas a partir do arquivo.

Vejamos um exemplo de uso da função genfromtxt sobre a base de dados Iris.

In [44]:
import numpy as np
# Caminho da base de dados é uma url disponível na internet (visite o link abaixo
# pelo navegador para título de curiosidade :))
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# Lê os dados a partir do caminho passado e armazena em uma matriz 2D chamada iris_2d
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [45]:
# matriz 2D criada com os dados da base Iris
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

11.A partir dos dados lidos na matriz iris_2d, filtre as linhas que possuem (coluna 3) > 1.5 e (coluna 1) < 5.0.

In [ ]:

vetor[(vetor > 10) & (vetor < 100)]
vetor[(vetor > 10) | (vetor >= 100)]

12.A partir dos dados lidos na matriz iris_2d, calcule a média e desvio padrão de cada coluna presente nos dados. Imprima o resultado.

13.Crie um repositório no Github e versione todos os códigos que desenvolveram nesta lista de exercícios.